name: gfm-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.13
  - numpy=1.26
  - pandas=1.5.3
  - shapely=1.8.5
  - geopandas<0.13
  - gdal
  - rasterio
  - fiona
  - h5py
  - rioxarray
  - scikit-learn
  - matplotlib
  - xarray<=2023.12.0
  - geemap
  - xlsxwriter
  - pip
  - pip:
      - torch==2.2.1
      - torchvision==0.17.1
      - torchmetrics==1.3.2
      - wandb==0.16.3
      - einops==0.7.0
      - earthengine-api==0.1.391
      - tqdm==4.66.2
      - geobench==1.0.0
      - types-requests
      - fast_pytorch_kmeans
      - satlaspretrain-models
      - timm
      - breizhcrops
      - ruff==0.2.0
      - mypy==1.8.0
