name: crf-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.24.0
  - rasterio=1.3.11
  - gdal=3.9.2
  - proj=9.4.1
  - shapely=2.0.6
  - pydensecrf
  - dask
  - dask-jobqueue
  - pip